# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'IrisLibrary' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for IrisLibrary
pod 'IrisSDKStatic', '~>0.4.0'
pod 'OneSignal', '~>2.11.0'
pod 'PlotPlugin', '2.3.1'

end
